#ifndef CONFIG_H
#define CONFIG_H

#define EMULATOR_WINDOW_TITLE "Chip8 Emulator"
#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32
#define CHIP8_WINDOW_SIZE_MULTIPLIER 10
#define CHIP8_DATA_REGISTERS 16
#define CHIP8_STACK_DEPTH 16
#define CHIP8_KEYS 16
#define CHIP8_CHARACTER_SET_ADDRESS 0x00

#endif